### Testar serviço
GET http://localhost:3000/ping

### Teste admin ping
GET http://localhost:3000/admin/ping

### Teste Login
POST http://localhost:3000/admin/login
content-type: application/json

{
    "password": "07122023"
}

### Teste com token
GET http://localhost:3000/admin/ping
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%07122023

### Get all events
GET http://localhost:3000/admin/events
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%07122023

### Get one event
GET http://localhost:3000/admin/events/clpvmf01c0000scdt1jhiwdas
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%07122023

### Create new Event
POST http://localhost:3000/admin/events
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%07122023

{
    "title": "Novo evento 2",
    "description": "Descrição do evento 2"
}