### Testar serviço
GET http://localhost:3000/ping

### Teste admin ping
GET http://localhost:3000/admin/ping

### Teste Login -- passar data do dia atual
POST http://localhost:3000/admin/login
content-type: application/json

{
    "password": "08122023"
}

### Teste com token
GET http://localhost:3000/admin/ping
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023

### Get all events
GET http://localhost:3000/admin/events
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023

### Get one event
GET http://localhost:3000/admin/events/clpvmf01c0000scdt1jhiwdas
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%08122023

### Create new Event
POST http://localhost:3000/admin/events
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023

{
    "title": "Novo evento 3",
    "description": "Descrição do evento 3",
    "grouped": true
}

### Update Event
PUT http://localhost:3000/admin/events/clpvmf01c0000scdt1jhiwdas
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%08122023

{
    "title": "Udpate evento",
    "description": "Update 2 descrição do evento 3",
    "grouped": true
}

### Delete Event
DELETE  http://localhost:3000/admin/events/clpvo7f180000z9nkho86exim
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%08122023

### Get All Groups
GET  http://localhost:3000/admin/events/clpwpih750000uznfag69l8rb/groups
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023

### Create new Group
POST http://localhost:3000/admin/events/clpwpih750000uznfag69l8rb/groups
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023

{
    "name": "Primeiro grupo no evento rb"  
}

### Update Group
PUT http://localhost:3000/admin/events/clpvmf01c0000scdt1jhiwdas/groups/clq0zq04y0001ubw2x03vnllx
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023

{
    "name": "Update 2 nome grupo"  
}

### Delete Group
DELETE http://localhost:3000/admin/events/clpvmf01c0000scdt1jhiwdas/groups/clq0zq04y0001ubw2x03vnllx
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023

### Get People
GET http://localhost:3000/admin/events/clpvmf01c0000scdt1jhiwdas/groups/clq0zq04y0001ubw2x03vnllx/people
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023

### Create People
POST http://localhost:3000/admin/events/clpvmf01c0000scdt1jhiwdas/groups/clq14xxgi0001k411i56nk3hr/people
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023

{
    "name": "Ronaldo",
    "cpf": "96282383121"
}

### Update People
PUT http://localhost:3000/admin/events/clpwpih750000uznfag69l8rb/groups/clq15yldh000ak411tjz7tvv6/people/clq1dpt5y0001n7enq62cn40w
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023

{
    "name": "Felipe França Lohmann",
    "cpf": "82833243"
}

### Delete Person
DELETE http://localhost:3000/admin/events/clpwpih750000uznfag69l8rb/groups/clq15yldh000ak411tjz7tvv6/people/clq1dpt5y0001n7enq62cn40w
Content-Type: application/json
Authorization: token jPADh8UPwqRNajhViXKQIsPET+QvJmIPvFvK3bepECA%11122023
